//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoteriaNacionalCR.LoteriaWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sorteo", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class Sorteo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoteriaNacionalCR.LoteriaWebService.Premio[] PremioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoteriaNacionalCR.LoteriaWebService.Premio[] Premio {
            get {
                return this.PremioField;
            }
            set {
                if ((object.ReferenceEquals(this.PremioField, value) != true)) {
                    this.PremioField = value;
                    this.RaisePropertyChanged("Premio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Premio", Namespace="http://schemas.datacontract.org/2004/07/AccesoDatos")]
    [System.SerializableAttribute()]
    public partial class Premio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoteriaNacionalCR.LoteriaWebService.Sorteo Sorteo1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int importanciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal montoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sorteoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoteriaNacionalCR.LoteriaWebService.Sorteo Sorteo1 {
            get {
                return this.Sorteo1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Sorteo1Field, value) != true)) {
                    this.Sorteo1Field = value;
                    this.RaisePropertyChanged("Sorteo1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int importancia {
            get {
                return this.importanciaField;
            }
            set {
                if ((this.importanciaField.Equals(value) != true)) {
                    this.importanciaField = value;
                    this.RaisePropertyChanged("importancia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal monto {
            get {
                return this.montoField;
            }
            set {
                if ((this.montoField.Equals(value) != true)) {
                    this.montoField = value;
                    this.RaisePropertyChanged("monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numero {
            get {
                return this.numeroField;
            }
            set {
                if ((this.numeroField.Equals(value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sorteo {
            get {
                return this.sorteoField;
            }
            set {
                if ((this.sorteoField.Equals(value) != true)) {
                    this.sorteoField = value;
                    this.RaisePropertyChanged("sorteo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoteriaWebService.ILoteriaNacional")]
    public interface ILoteriaNacional {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoteriaNacional/TipoCambio", ReplyAction="http://tempuri.org/ILoteriaNacional/TipoCambioResponse")]
        double TipoCambio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoteriaNacional/TipoCambio", ReplyAction="http://tempuri.org/ILoteriaNacional/TipoCambioResponse")]
        System.Threading.Tasks.Task<double> TipoCambioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoteriaNacional/AgregarSorteo", ReplyAction="http://tempuri.org/ILoteriaNacional/AgregarSorteoResponse")]
        void AgregarSorteo(LoteriaNacionalCR.LoteriaWebService.Sorteo oSorteo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoteriaNacional/AgregarSorteo", ReplyAction="http://tempuri.org/ILoteriaNacional/AgregarSorteoResponse")]
        System.Threading.Tasks.Task AgregarSorteoAsync(LoteriaNacionalCR.LoteriaWebService.Sorteo oSorteo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoteriaNacionalChannel : LoteriaNacionalCR.LoteriaWebService.ILoteriaNacional, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoteriaNacionalClient : System.ServiceModel.ClientBase<LoteriaNacionalCR.LoteriaWebService.ILoteriaNacional>, LoteriaNacionalCR.LoteriaWebService.ILoteriaNacional {
        
        public LoteriaNacionalClient() {
        }
        
        public LoteriaNacionalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoteriaNacionalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoteriaNacionalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoteriaNacionalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double TipoCambio() {
            return base.Channel.TipoCambio();
        }
        
        public System.Threading.Tasks.Task<double> TipoCambioAsync() {
            return base.Channel.TipoCambioAsync();
        }
        
        public void AgregarSorteo(LoteriaNacionalCR.LoteriaWebService.Sorteo oSorteo) {
            base.Channel.AgregarSorteo(oSorteo);
        }
        
        public System.Threading.Tasks.Task AgregarSorteoAsync(LoteriaNacionalCR.LoteriaWebService.Sorteo oSorteo) {
            return base.Channel.AgregarSorteoAsync(oSorteo);
        }
    }
}
